// Diambil dari semua pemanggilan recordAuditLog() di backend (grep modul).
export const MODUL_OPTIONS = [
  'AUTH', 'CELL_GROUP', 'EVENT', 'EVENT_KEHADIRAN', 'JEMAAT', 'LAPORAN', 'SCORING', 'USER', 'VOLUNTEER',
] as const;

export const AKSI_OPTIONS = [
  'ACTIVATE', 'ACTIVATE_CG', 'ACTIVATE_USER', 'ADD_MEETING_PHOTO', 'ADD_MEMBER_CG',
  'ASSIGN_VOLUNTEER', 'CANCEL_VOLUNTEER_ASSIGNMENT', 'CREATE', 'CREATE_CG', 'CREATE_MEETING',
  'CREATE_USER', 'DEACTIVATE_CG', 'DEACTIVATE_USER', 'DELETE', 'DELETE_MEETING_PHOTO',
  'EXPORT', 'INPUT_ABSENSI_CG', 'LOGIN', 'LOGOUT', 'REGISTER_VOLUNTEER', 'REMOVE_MEMBER_CG',
  'REPLACE_VOLUNTEER', 'RESET_PASSWORD', 'UNREGISTER_VOLUNTEER', 'UPDATE', 'UPDATE_CG',
  'UPDATE_MEETING', 'UPDATE_STATUS', 'UPDATE_VOLUNTEER_NEEDS', 'VIEW_SENSITIVE',
] as const;